### ISSUE TITLE
Error: `bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)` [Next.js - 14.2.5 & @solana/web3.js: ^1.95.2]

### ISSUE THREAD

**Issue by Rishabh-Singh-Codes** [solana-labs/solana-web3.js#3097] opened 2024-08-12 16:23 UTC
I am encountering the following error when I am using the @solana/web3.js with Next.JS.

`bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)`

Because of this issue, I am not able to build the project and host it. 

Error I'm encountering while building:

<img width="986" alt="Screenshot 2024-08-12 at 9 33 34 PM" src="https://github.com/user-attachments/assets/a6783d08-323c-4ae3-8274-b88861f5da5f">

Dependencies:

"dependencies": {
    "@prisma/client": "^5.17.0",
    "@solana/spl-token": "^0.4.8",
    "@solana/web3.js": "^1.95.2",
    "axios": "^1.7.3",
    "next": "14.2.5",
    "next-auth": "^4.24.7",
    "prisma": "^5.17.0",
    "react": "^18",
    "react-dom": "^18",
    "react-icons": "^5.2.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.5",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }

**Comment by buffalojoec** [comment] 2024-08-12 19:07
Duplicate of https://github.com/solana-labs/solana-web3.js/issues/2916

**Closed by buffalojoec** 2024-08-12 19:07 UTC
